Repository microwavekonijn/ps2census, pull requests merged in 2022-12, with the labels that each got.

#90 fix(dependencies): optional dependencies not being optional
  package-lock.json
  package.json
Labels: bug, dependencies

#91 Feat/improved event types
  src/client/census.client.ts
  src/client/concerns/stream-filter.contract.ts
  src/client/constants/ps2.constants.ts
  src/client/events/achievement-earned.event.ts
  src/client/events/base/attacker.event.ts
  src/client/events/base/character-world.event.ts
  src/client/events/base/character.event.ts
  src/client/events/base/ps2.event.ts
  src/client/events/base/world.event.ts
  src/client/events/base/zone.event.ts
  src/client/events/battle-rank-up.event.ts
  src/client/events/continent-lock.event.ts
  src/client/events/continent-unlock.event.ts
  src/client/events/death.event.ts
  src/client/events/facility-control.event.ts
  src/client/events/gain-experience.event.ts
  src/client/events/item-added.event.ts
  src/client/events/metagame.event.ts
  src/client/events/player-facility-capture.event.ts
  src/client/events/player-facility-defend.event.ts
  src/client/events/player-login.event.ts
  src/client/events/player-logout.event.ts
  src/client/events/skill-added.event.ts
  src/client/events/vehicle-destroy.event.ts
  src/client/stream.handler.ts
  src/client/utils/duplicate-filter.ts
Labels: enhancement

#94 fix(stream): removed continent unlock event beacuse it was never a thing
  src/client/census.client.ts
  src/client/events/continent-unlock.event.ts
  src/client/events/index.ts
  src/client/stream.handler.ts
  src/stream/types/ps2.events.ts
Labels: enhancement, chore

#93 feat(stream): add browser support
  package-lock.json
  package.json
  src/client/command.handler.ts
  src/client/stream.handler.ts
  src/client/utils/decaying-set.ts
  src/stream/stream.client.ts
  src/utils/next-tick.ts
Labels: enhancement

#95 Chore/prepare release
  README.md
  docs/Rest.md
  docs/Stream.md
  src/client/managers/character.manager.ts
  src/client/stream.manager.ts
  src/client/subscription.manager.ts
  src/stream/stream.client.ts
Labels: documentation, chore
